### PR TITLE
Update to Phoenix 4.3.0 and HBase 0.98.9

### PR DESCRIPTION
**Pull request by jmahonin**
Needed to add an ugly lookup table since the PDataType enum got
broken up. There's probably a much nicer way around type erasure
but I don't know it.

### CODE REVIEW

**Comment by robdaemon** [comment]
Ugh, that's a messy change from the Phoenix team. :(

**Comment by robdaemon** [comment]
@nenadl - maybe you want to merge this? I'm not a collaborator on this repo anymore.

**Comment by jmahonin** [comment]
If the patch is useful to either of you, I can clean up the comments (or anything else suggested). If you know of a better way to get this working, I'm all ears as well.

**Comment by robdaemon** [comment]
@nenadl - I don't have access to merge it myself anymore. I got booted off the repo again :)

**Pull request merged**
